### ISSUE TITLE
&apos

### ISSUE THREAD

**Issue by luzlab** [voidberg/eslint-bamboo-formatter#3]
In Bamboo report, `&apos;` appears instead of `'`. I'm using Bamboo 6.4 and node 6.10.

I can work on a PR if you'd like

**Comment by voidberg** [comment]
Please do, I will have some time to look at this only next week unfortunately.

**Comment by luzlab** [comment]
I opened a PR #4.

**Comment by luzlab** [comment]
Thank you for merging the PR. Don't forget to bump the version and deploy to npm.

**Comment by voidberg** [comment]
New version was published today.
